services:

  db:
    image: mariadb:10-focal
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=book_buddy
      - MYSQL_ROOT_PASSWORD=test_pass_1
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=test_pass
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=./app/app.py

volumes:
  db-data:
